"""Interactions with the 1Password `op` CLI."""

import json
import subprocess
from datetime import datetime, timezone

from .constants import (
    DATE_FORMAT,
    ONE_PASSWORD_FILE_PATH_FIELD_NAME,
    ONE_PASSWORD_NOTES_CONTENT_FIELD_NAME,
    ONE_PASSWORD_SECURE_NOTE_CATEGORY,
)
from .errors import raise_error
from .logs import console, debug_command, logger
from .prompts import prompt_secret_diff
from .utils import first


def run_1password_command(*args, vault=None, json_output=True, status_message=None):
    command_args = ["op", *args]

    if vault is not None:
        command_args.extend(["--vault", vault])

    if json_output:
        command_args.extend(["--format", "json"])

    def run_command():
        try:
            output = subprocess.check_output(command_args)  # noqa: S603
        except subprocess.CalledProcessError as e:
            debug_command(command_args, returncode=e.returncode)
            raise_error(f"1Password command failed with exit code {e.returncode}")

        debug_command(command_args, output=output, returncode=0)
        return output

    if status_message:
        with console.status(f"[bold cyan]{status_message}...", spinner="dots"):
            return run_command()
    return run_command()


def make_1password_custom_field_cli_argument(field_name, value):
    prefix = "Generated by 1password-secrets"
    return f"{prefix}.{field_name}[text]={value}"


def make_last_edited_1password_custom_field_cli_argument():
    now_formatted = datetime.now(tz=timezone.utc).strftime(DATE_FORMAT)

    return make_1password_custom_field_cli_argument(
        field_name="last edited at",
        value=now_formatted,
    )


def get_1password_env_file_item_id(title_substring, vault=None):
    secure_notes = json.loads(
        run_1password_command(
            "item",
            "list",
            "--categories",
            ONE_PASSWORD_SECURE_NOTE_CATEGORY,
            vault=vault,
            status_message="Searching 1Password",
        )
    )

    item_ids = [item["id"] for item in secure_notes if title_substring in item["title"].split(" ")]

    if len(item_ids) == 0:
        raise_error(
            "No 1password secure note found with a name containing "
            "{title_substring} {vault_prefix_message}".format(
                title_substring=repr(title_substring),
                vault_prefix_message=f"in vault {vault}" if vault else "across all vaults",
            )
        )

    if len(item_ids) > 1:
        raise_error(
            f"Found {len(item_ids)} 1password secure notes with a name containing "
            f"{title_substring!r}, expected one. "
            "Rename or use different 1password vaults in combination with the `--vault` option."
        )

    return item_ids[0]


def get_item_from_1password(item_id, vault=None):
    return json.loads(
        run_1password_command(
            "item", "get", item_id, vault=vault, status_message="Fetching from 1Password"
        )
    )


def get_envs_from_1password(item_id, vault=None) -> str:
    item = get_item_from_1password(item_id, vault=vault)

    result = first(
        field.get("value")
        for field in item["fields"]
        if field["id"] == ONE_PASSWORD_NOTES_CONTENT_FIELD_NAME
    )
    if result is None or result == "":
        raise_error("Empty secrets, aborting")

    return result or ""


def get_filename_from_1password(item_id, vault=None):
    item = get_item_from_1password(item_id, vault=vault)

    return first(
        field.get("value")
        for field in item["fields"]
        if field["label"] == ONE_PASSWORD_FILE_PATH_FIELD_NAME
    )


def get_item_share_link(item_id, vault=None) -> str:
    return (
        run_1password_command(
            "item",
            "get",
            item_id,
            "--share-link",
            vault=vault,
            json_output=False,
        )
        .decode("utf-8")
        .strip()
    )


def create_1password_secrets(file_path, raw_secrets, title, vault=None):
    logger.debug("Creating 1password secret note")

    return json.loads(
        run_1password_command(
            "item",
            "create",
            "--category",
            ONE_PASSWORD_SECURE_NOTE_CATEGORY,
            "--title",
            title,
            f"{ONE_PASSWORD_NOTES_CONTENT_FIELD_NAME}={raw_secrets}",
            f"{ONE_PASSWORD_FILE_PATH_FIELD_NAME}[text]={file_path}",
            make_last_edited_1password_custom_field_cli_argument(),
            vault=vault,
            status_message="Creating secret in 1Password",
        )
    )


def update_1password_secrets(item_id, new_raw_secrets, previous_raw_secrets=None, vault=None):
    if previous_raw_secrets is None:
        previous_raw_secrets = get_envs_from_1password(item_id)

    prompt_secret_diff(
        previous_raw_secrets=previous_raw_secrets,
        new_raw_secrets=new_raw_secrets,
    )

    logger.debug(f"Updating 1password secret note content for item {item_id!r}")
    run_1password_command(
        "item",
        "edit",
        item_id,
        f"notesPlain={new_raw_secrets}",
        make_last_edited_1password_custom_field_cli_argument(),
        vault=vault,
        status_message="Updating 1Password",
    )


def update_1password_custom_field(item_id, field, value, vault=None):
    logger.debug(f"Updating 1password custom field for item {item_id!r}")
    run_1password_command(
        "item",
        "edit",
        item_id,
        make_1password_custom_field_cli_argument(field, value),
        vault=vault,
        status_message="Updating metadata",
    )
